### PR TITLE
Lokoban

### PR DESCRIPTION
**Pull request by RojjaCebolla**
inspired by https://github.com/demogorgon22/notdnethack/blob/2021.05.21/dat/sokoban.des

### CODE REVIEW

**Review by NullCGT — COMMENTED** [review]
I like it! Thought: What if we add the soko1 and and soko3 variants as alternate levels?

**Comment by RojjaCebolla** [comment]
> I like it! Thought: What if we add the soko1 and and soko3 variants as alternate levels?

which variants, from which variant?

**Comment by RojjaCebolla** [comment]
tested: 
image

**Comment by RojjaCebolla** [comment]
resolved conflicts 'n tested 
image

**Comment by RojjaCebolla** [comment]
I've tested that each of the new soko levels is solvable, and for me these new additions are relatively non-frustrating, learnable levels. 3e, if you don't use the wiki solution, requires you to sit and think for a few moments about which boulder to move, you can't just kinda "get started". But 3a has a similar quirk, where there are 3 options right in your face and only one is good.

One thing that might be a cool improvement in general for soko, is instead of calling the level "Soko 4" or whatever, if it actually said "4d" so that people can look it up on the wiki even more easily than they do now.

**Review by NullCGT — APPROVED** [review]
Approved!

**Pull request merged**
