### PR TITLE
can't leave without indy's lucky hat

### PR DESCRIPTION
**Pull request by RojjaCebolla**
wearing it adjusts luck up by 1, and it can be enchanted to +7

### CODE REVIEW

**Comment by NullCGT** [comment]
Once conflicts are resolved, I can merge.

**Comment by RojjaCebolla** [comment]
I can merge 😁

**Comment by RojjaCebolla** [comment]
(thought it'd be ok since you already seem to have finished up with that branch)

**Comment by RojjaCebolla** [comment]
changing the base branch to Spl-1.0 looked too messy

**Pull request merged**
